package com.javath.mapping;

// Generated Aug 7, 2013 9:38:49 AM by Hibernate Tools 4.0.0

/**
 * BualuangBoardDaily generated by hbm2java
 */
public class BualuangBoardDaily implements java.io.Serializable {

	private BualuangBoardDailyId id;
	private Float open;
	private Float high;
	private Float low;
	private Float close;
	private Long volume;
	private Double value;

	public BualuangBoardDaily() {
	}

	public BualuangBoardDaily(BualuangBoardDailyId id) {
		this.id = id;
	}

	public BualuangBoardDaily(BualuangBoardDailyId id, Float open, Float high,
			Float low, Float close, Long volume, Double value) {
		this.id = id;
		this.open = open;
		this.high = high;
		this.low = low;
		this.close = close;
		this.volume = volume;
		this.value = value;
	}

	public BualuangBoardDailyId getId() {
		return this.id;
	}

	public void setId(BualuangBoardDailyId id) {
		this.id = id;
	}

	public Float getOpen() {
		return this.open;
	}

	public void setOpen(Float open) {
		this.open = open;
	}

	public Float getHigh() {
		return this.high;
	}

	public void setHigh(Float high) {
		this.high = high;
	}

	public Float getLow() {
		return this.low;
	}

	public void setLow(Float low) {
		this.low = low;
	}

	public Float getClose() {
		return this.close;
	}

	public void setClose(Float close) {
		this.close = close;
	}

	public Long getVolume() {
		return this.volume;
	}

	public void setVolume(Long volume) {
		this.volume = volume;
	}

	public Double getValue() {
		return this.value;
	}

	public void setValue(Double value) {
		this.value = value;
	}

}
