package com.javath.mapping;

// Generated Sep 30, 2013 2:01:59 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * CalculatorRsi generated by hbm2java
 */
public class CalculatorRsi implements java.io.Serializable {

	private CalculatorRsiId id;
	private Date datetime;
	private Double smaGain;
	private Double smaLoss;

	public CalculatorRsi() {
	}

	public CalculatorRsi(CalculatorRsiId id) {
		this.id = id;
	}

	public CalculatorRsi(CalculatorRsiId id, Date datetime, Double smaGain,
			Double smaLoss) {
		this.id = id;
		this.datetime = datetime;
		this.smaGain = smaGain;
		this.smaLoss = smaLoss;
	}

	public CalculatorRsiId getId() {
		return this.id;
	}

	public void setId(CalculatorRsiId id) {
		this.id = id;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public Double getSmaGain() {
		return this.smaGain;
	}

	public void setSmaGain(Double smaGain) {
		this.smaGain = smaGain;
	}

	public Double getSmaLoss() {
		return this.smaLoss;
	}

	public void setSmaLoss(Double smaLoss) {
		this.smaLoss = smaLoss;
	}

}
