package com.javath.mapping;

// Generated Sep 30, 2013 2:01:59 PM by Hibernate Tools 4.0.0

/**
 * IndicatorRsi generated by hbm2java
 */
public class IndicatorRsi implements java.io.Serializable {

	private IndicatorRsiId id;
	private Double rsi;

	public IndicatorRsi() {
	}

	public IndicatorRsi(IndicatorRsiId id) {
		this.id = id;
	}

	public IndicatorRsi(IndicatorRsiId id, Double rsi) {
		this.id = id;
		this.rsi = rsi;
	}

	public IndicatorRsiId getId() {
		return this.id;
	}

	public void setId(IndicatorRsiId id) {
		this.id = id;
	}

	public Double getRsi() {
		return this.rsi;
	}

	public void setRsi(Double rsi) {
		this.rsi = rsi;
	}

}
