package com.javath.mapping;

// Generated Sep 30, 2013 2:01:59 PM by Hibernate Tools 4.0.0

/**
 * ParameterRsi generated by hbm2java
 */
public class ParameterRsi implements java.io.Serializable {

	private short id;
	private Integer period;
	private String tableName;
	private String columnName;

	public ParameterRsi() {
	}

	public ParameterRsi(short id) {
		this.id = id;
	}

	public ParameterRsi(short id, Integer period, String tableName,
			String columnName) {
		this.id = id;
		this.period = period;
		this.tableName = tableName;
		this.columnName = columnName;
	}

	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	public Integer getPeriod() {
		return this.period;
	}

	public void setPeriod(Integer period) {
		this.period = period;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getColumnName() {
		return this.columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}

}
