package com.javath.mapping;
// Generated Aug 4, 2013 4:58:19 PM by Hibernate Tools 4.0.0



/**
 * SettradeBoard generated by hbm2java
 */
public class SettradeBoard  implements java.io.Serializable {


     private SettradeBoardId id;
     private Float last;
     private Float open;
     private Float high;
     private Float low;
     private Float bid;
     private Long bidVolume;
     private Float offer;
     private Long offerVolume;
     private Long volume;
     private Double value;

    public SettradeBoard() {
    }

	
    public SettradeBoard(SettradeBoardId id) {
        this.id = id;
    }
    public SettradeBoard(SettradeBoardId id, Float last, Float open, Float high, Float low, Float bid, Long bidVolume, Float offer, Long offerVolume, Long volume, Double value) {
       this.id = id;
       this.last = last;
       this.open = open;
       this.high = high;
       this.low = low;
       this.bid = bid;
       this.bidVolume = bidVolume;
       this.offer = offer;
       this.offerVolume = offerVolume;
       this.volume = volume;
       this.value = value;
    }
   
    public SettradeBoardId getId() {
        return this.id;
    }
    
    public void setId(SettradeBoardId id) {
        this.id = id;
    }
    public Float getLast() {
        return this.last;
    }
    
    public void setLast(Float last) {
        this.last = last;
    }
    public Float getOpen() {
        return this.open;
    }
    
    public void setOpen(Float open) {
        this.open = open;
    }
    public Float getHigh() {
        return this.high;
    }
    
    public void setHigh(Float high) {
        this.high = high;
    }
    public Float getLow() {
        return this.low;
    }
    
    public void setLow(Float low) {
        this.low = low;
    }
    public Float getBid() {
        return this.bid;
    }
    
    public void setBid(Float bid) {
        this.bid = bid;
    }
    public Long getBidVolume() {
        return this.bidVolume;
    }
    
    public void setBidVolume(Long bidVolume) {
        this.bidVolume = bidVolume;
    }
    public Float getOffer() {
        return this.offer;
    }
    
    public void setOffer(Float offer) {
        this.offer = offer;
    }
    public Long getOfferVolume() {
        return this.offerVolume;
    }
    
    public void setOfferVolume(Long offerVolume) {
        this.offerVolume = offerVolume;
    }
    public Long getVolume() {
        return this.volume;
    }
    
    public void setVolume(Long volume) {
        this.volume = volume;
    }
    public Double getValue() {
        return this.value;
    }
    
    public void setValue(Double value) {
        this.value = value;
    }




}


