package com.javath.mapping;

// Generated Aug 4, 2013 5:35:48 PM by Hibernate Tools 4.0.0

/**
 * SettradeIndex generated by hbm2java
 */
public class SettradeIndex implements java.io.Serializable {

	private SettradeIndexId id;
	private Float last;
	private Float high;
	private Float low;
	private Long volume;
	private Double value;

	public SettradeIndex() {
	}

	public SettradeIndex(SettradeIndexId id) {
		this.id = id;
	}

	public SettradeIndex(SettradeIndexId id, Float last, Float high, Float low,
			Long volume, Double value) {
		this.id = id;
		this.last = last;
		this.high = high;
		this.low = low;
		this.volume = volume;
		this.value = value;
	}

	public SettradeIndexId getId() {
		return this.id;
	}

	public void setId(SettradeIndexId id) {
		this.id = id;
	}

	public Float getLast() {
		return this.last;
	}

	public void setLast(Float last) {
		this.last = last;
	}

	public Float getHigh() {
		return this.high;
	}

	public void setHigh(Float high) {
		this.high = high;
	}

	public Float getLow() {
		return this.low;
	}

	public void setLow(Float low) {
		this.low = low;
	}

	public Long getVolume() {
		return this.volume;
	}

	public void setVolume(Long volume) {
		this.volume = volume;
	}

	public Double getValue() {
		return this.value;
	}

	public void setValue(Double value) {
		this.value = value;
	}

}
