package com.javath.mapping;
// Generated Aug 4, 2013 4:58:19 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * StreamingTickerId generated by hbm2java
 */
public class StreamingTickerId  implements java.io.Serializable {


     private Date date;
     private short market;
     private int sequence;

    public StreamingTickerId() {
    }

    public StreamingTickerId(Date date, short market, int sequence) {
       this.date = date;
       this.market = market;
       this.sequence = sequence;
    }
   
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public short getMarket() {
        return this.market;
    }
    
    public void setMarket(short market) {
        this.market = market;
    }
    public int getSequence() {
        return this.sequence;
    }
    
    public void setSequence(int sequence) {
        this.sequence = sequence;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StreamingTickerId) ) return false;
		 StreamingTickerId castOther = ( StreamingTickerId ) other; 
         
		 return ( (this.getDate()==castOther.getDate()) || ( this.getDate()!=null && castOther.getDate()!=null && this.getDate().equals(castOther.getDate()) ) )
 && (this.getMarket()==castOther.getMarket())
 && (this.getSequence()==castOther.getSequence());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDate() == null ? 0 : this.getDate().hashCode() );
         result = 37 * result + this.getMarket();
         result = 37 * result + this.getSequence();
         return result;
   }   


}


