package com.javath.mapping;

// Generated Sep 30, 2013 2:01:59 PM by Hibernate Tools 4.0.0

/**
 * StreamingOrder generated by hbm2java
 */
public class StreamingOrder implements java.io.Serializable {

	private StreamingOrderId id;
	private Long orderNo;
	private String side;
	private Double price;
	private Integer volume;
	private Integer matched;
	private Integer balance;
	private Integer cancelled;
	private String status;
	private Long orderBroker;

	public StreamingOrder() {
	}

	public StreamingOrder(StreamingOrderId id) {
		this.id = id;
	}

	public StreamingOrder(StreamingOrderId id, Long orderNo, String side,
			Double price, Integer volume, Integer matched, Integer balance,
			Integer cancelled, String status, Long orderBroker) {
		this.id = id;
		this.orderNo = orderNo;
		this.side = side;
		this.price = price;
		this.volume = volume;
		this.matched = matched;
		this.balance = balance;
		this.cancelled = cancelled;
		this.status = status;
		this.orderBroker = orderBroker;
	}

	public StreamingOrderId getId() {
		return this.id;
	}

	public void setId(StreamingOrderId id) {
		this.id = id;
	}

	public Long getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(Long orderNo) {
		this.orderNo = orderNo;
	}

	public String getSide() {
		return this.side;
	}

	public void setSide(String side) {
		this.side = side;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Integer getVolume() {
		return this.volume;
	}

	public void setVolume(Integer volume) {
		this.volume = volume;
	}

	public Integer getMatched() {
		return this.matched;
	}

	public void setMatched(Integer matched) {
		this.matched = matched;
	}

	public Integer getBalance() {
		return this.balance;
	}

	public void setBalance(Integer balance) {
		this.balance = balance;
	}

	public Integer getCancelled() {
		return this.cancelled;
	}

	public void setCancelled(Integer cancelled) {
		this.cancelled = cancelled;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Long getOrderBroker() {
		return this.orderBroker;
	}

	public void setOrderBroker(Long orderBroker) {
		this.orderBroker = orderBroker;
	}

}
