package com.javath.mapping;
// Generated Sep 17, 2013 2:05:15 PM by Hibernate Tools 4.0.0



/**
 * StreamingOrder generated by hbm2java
 */
public class StreamingOrder  implements java.io.Serializable {


     private StreamingOrderId id;
     private Long orderNo;
     private String side;
     private Double price;
     private Integer volume;
     private Integer match;
     private Integer balance;
     private Integer cancelled;
     private String status;

    public StreamingOrder() {
    }

	
    public StreamingOrder(StreamingOrderId id) {
        this.id = id;
    }
    public StreamingOrder(StreamingOrderId id, Long orderNo, String side, Double price, Integer volume, Integer match, Integer balance, Integer cancelled, String status) {
       this.id = id;
       this.orderNo = orderNo;
       this.side = side;
       this.price = price;
       this.volume = volume;
       this.match = match;
       this.balance = balance;
       this.cancelled = cancelled;
       this.status = status;
    }
   
    public StreamingOrderId getId() {
        return this.id;
    }
    
    public void setId(StreamingOrderId id) {
        this.id = id;
    }
    public Long getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }
    public String getSide() {
        return this.side;
    }
    
    public void setSide(String side) {
        this.side = side;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Integer getVolume() {
        return this.volume;
    }
    
    public void setVolume(Integer volume) {
        this.volume = volume;
    }
    public Integer getMatch() {
        return this.match;
    }
    
    public void setMatch(Integer match) {
        this.match = match;
    }
    public Integer getBalance() {
        return this.balance;
    }
    
    public void setBalance(Integer balance) {
        this.balance = balance;
    }
    public Integer getCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(Integer cancelled) {
        this.cancelled = cancelled;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


