package com.javath.mapping;

// Generated Aug 4, 2013 5:35:48 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * StreamingBidsOffersId generated by hbm2java
 */
public class StreamingBidsOffersId implements java.io.Serializable {

	private String symbol;
	private Date date;
	private float price;

	public StreamingBidsOffersId() {
	}

	public StreamingBidsOffersId(String symbol, Date date, float price) {
		this.symbol = symbol;
		this.date = date;
		this.price = price;
	}

	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StreamingBidsOffersId))
			return false;
		StreamingBidsOffersId castOther = (StreamingBidsOffersId) other;

		return ((this.getSymbol() == castOther.getSymbol()) || (this
				.getSymbol() != null && castOther.getSymbol() != null && this
				.getSymbol().equals(castOther.getSymbol())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null
						&& castOther.getDate() != null && this.getDate()
						.equals(castOther.getDate())))
				&& (this.getPrice() == castOther.getPrice());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSymbol() == null ? 0 : this.getSymbol().hashCode());
		result = 37 * result
				+ (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (int) this.getPrice();
		return result;
	}

}
