#!/bin/sh

EXEC=/usr/bin/jsvc
JAVA_HOME=/usr/bin/java
CLASS_PATH=lib/commons-daemon.jar
CLASS=com.javath.Service
USER=user
PID=/tmp/service.pid
LOG_OUT=/tmp/service.out
LOG_ERR=/tmp/service.err

do_exec()
{
    $EXEC -home "$JAVA_HOME" -cp $CLASS_PATH -user $USER -outfile $LOG_OUT -errfile $LOG_ERR -pidfile $PID $1 $CLASS
}

case "$1" in
    start)
        do_exec
            ;;
    stop)
        do_exec "-stop"
            ;;
    restart)
        if [ -f "$PID" ]; then
            do_exec "-stop"
            do_exec
        else
            echo "service not running, will do nothing"
            exit 1
        fi
            ;;
    *)
            echo "usage: $0 {start|stop|restart}" >&2
            exit 3
            ;;
esac